version: '3.9'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: money-map
    ports:
      - 5432:5432

volumes:
  pgdata: