spring:
  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: true
    baseline-on-migrate: true
    table: _schema_version
    connect-retries: 10
    out-of-order: true
  application:
    name: api
  datasource:
    url: jdbc:postgresql://localhost:5432/money-map
    username: postgres
    password: example
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
